# Generated by Django 4.0.4 on 2022-05-19 19:19

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_profile_profile_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_img',
            field=cloudinary.models.CloudinaryField(default='default_image', max_length=255, verbose_name='profile_image'),
        ),
    ]
