# Generated by Django 4.0.4 on 2022-07-03 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_alter_profile_profile_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='profile_email',
        ),
    ]
