# Generated by Django 4.0.4 on 2022-07-04 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0009_alter_profile_profile_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='profile_email',
            new_name='email',
        ),
    ]
