# Generated by Django 4.0.4 on 2022-07-21 17:49

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0010_rename_profile_email_profile_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_img',
            field=cloudinary.models.CloudinaryField(default='default_image', max_length=255, verbose_name='Profile image'),
        ),
    ]
