# Generated by Django 4.0.4 on 2022-05-19 10:53

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('profiles', '0001_initial'),
        ('blog_post', '0002_remove_category_author_blogcomment_blog_post_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BlogComment',
            new_name='Comment',
        ),
        migrations.RenameModel(
            old_name='BlogPost',
            new_name='Post',
        ),
    ]
