# Generated by Django 4.0.4 on 2022-05-19 15:04

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_post', '0003_rename_blogcomment_comment_rename_blogpost_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='category_img',
            field=cloudinary.models.CloudinaryField(default='', max_length=255, verbose_name='image'),
        ),
        migrations.AddField(
            model_name='post',
            name='post_img',
            field=cloudinary.models.CloudinaryField(default='', max_length=255, verbose_name='image'),
        ),
    ]
