# Generated by Django 4.0.4 on 2022-05-22 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_post', '0007_post_meta_description_post_publish_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'categories'},
        ),
    ]
