# Generated by Django 4.0.4 on 2022-05-25 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_post', '0008_alter_category_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='approved',
            field=models.CharField(choices=[('U', 'Unhandled'), ('A', 'Approve'), ('D', 'Deny')], default='Unhandled', max_length=9),
        ),
    ]
