# Generated by Django 4.0.4 on 2022-05-25 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_alter_profile_profile_img'),
        ('blog_post', '0010_rename_approved_comment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='likes',
            field=models.ManyToManyField(blank=True, default=0, related_name='post_likes', to='profiles.profile'),
        ),
    ]
