# Generated by Django 4.0.4 on 2022-06-02 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_post', '0013_alter_post_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='published',
            field=models.IntegerField(choices=[(0, 'Draft'), (1, 'Publish')], default=0),
        ),
    ]
