# Generated by Django 4.0.4 on 2022-06-29 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_post', '0022_remove_post_liked'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='liked',
            field=models.BooleanField(default=False),
        ),
    ]
