# Generated by Django 4.0.4 on 2022-07-05 12:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog_post', '0029_alter_like_author_alter_like_blog_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='blog_post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_likes', to='blog_post.post'),
        ),
    ]
