# Generated by Django 4.0.4 on 2022-07-12 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_post', '0030_alter_like_blog_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='status',
        ),
    ]
