# Generated by Django 4.0.4 on 2022-05-19 19:19

import cloudinary.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_alter_profile_profile_img'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0004_category_category_img_post_post_img'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='status',
            new_name='approved',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='status',
            new_name='published',
        ),
        migrations.AlterField(
            model_name='category',
            name='category_img',
            field=cloudinary.models.CloudinaryField(default='default_image', max_length=255, verbose_name='category_image'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments_author', to='profiles.profile'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='blog_post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_comments', to='blog.post'),
        ),
        migrations.AlterField(
            model_name='like',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes_author', to='profiles.profile'),
        ),
        migrations.AlterField(
            model_name='like',
            name='blog_post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_likes', to='blog.post'),
        ),
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_author', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_category', to='blog.category'),
        ),
        migrations.AlterField(
            model_name='post',
            name='likes',
            field=models.ManyToManyField(default=0, related_name='post_likes', to='profiles.profile'),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_img',
            field=cloudinary.models.CloudinaryField(default='default_image', max_length=255, verbose_name='post_image'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
